'use strict';
async function generatePracticalSpecificationPDF({course,assignment,profile,data,specificationId}){
 const W=1240,H=1754,M=82,TEAL='#0f3033',GREEN='#22c55e',INK='#17282b',MUTED='#617174',PALE='#f1f7f4',WHITE='#ffffff';
 const c=document.createElement('canvas');c.width=W;c.height=H;const x=c.getContext('2d');
 const clean=v=>String(v??'').replace(/[\u2010-\u2015]/g,'-').replace(/[\u2018\u2019]/g,"'").replace(/[\u201c\u201d]/g,'"');
 const wrap=(text,max,font='400 22px Arial')=>{x.font=font;const out=[];for(const p of clean(text||'-').split(/\n/)){let line='';for(const w of p.split(/\s+/)){const t=line?line+' '+w:w;if(x.measureText(t).width>max&&line){out.push(line);line=w}else line=t}out.push(line||' ')}return out};
 const drawLines=(text,px,py,max,lineH=30,font='400 22px Arial',limit=12)=>{x.font=font;x.fillStyle=INK;const lines=wrap(text,max,font).slice(0,limit);lines.forEach((l,i)=>x.fillText(l,px,py+i*lineH));return py+lines.length*lineH};
 const parse=window.practicalSpecificationSections?window.practicalSpecificationSections(data.activity):{title:'Practical task',description:data.activity,dimensions:'Refer to task',materials:'Select suitable materials',requirements:'Complete safely and accurately',difficulty:data.activityTaskType||'Custom',duration:'Set by assessor'};
 x.fillStyle=WHITE;x.fillRect(0,0,W,H);x.fillStyle=GREEN;x.fillRect(0,0,W,18);x.fillStyle=TEAL;x.fillRect(M,54,W-2*M,138);x.fillStyle=WHITE;x.font='800 25px Arial';x.fillText('APPRENTICE+  |  PRACTICAL TASK SPECIFICATION',M+28,98);x.font='700 38px Arial';x.fillText(clean(parse.title).slice(0,52),M+28,151);x.font='600 18px Arial';x.fillText(`Practical Assessment ${assignment.n}  |  ${clean(course.name)}`,M+28,181);
 let y=228;x.fillStyle=PALE;x.fillRect(M,y,W-2*M,132);const meta=[['SPECIFICATION ID',specificationId],['DIFFICULTY',parse.difficulty],['ESTIMATED DURATION',parse.duration],['DATE ISSUED',data.activityGeneratedAt?new Date(data.activityGeneratedAt).toLocaleDateString('en-GB'):new Date().toLocaleDateString('en-GB')],['LEARNER',profile?.fullName||'-'],['COURSE STANDARD',course.standard||'-']];meta.forEach((m,i)=>{const col=i%3,row=Math.floor(i/3),px=M+24+col*350,py=y+28+row*58;x.fillStyle=MUTED;x.font='700 14px Arial';x.fillText(m[0],px,py);x.fillStyle=INK;x.font='700 19px Arial';x.fillText(clean(m[1]).slice(0,31),px,py+25)});y+=176;
 const section=(title,text,maxLines=12)=>{x.fillStyle=TEAL;x.font='700 24px Arial';x.fillText(title,M,y);x.fillStyle=GREEN;x.fillRect(M,y+12,W-2*M,4);y+=48;y=drawLines(text,M,y,W-2*M,29,'400 21px Arial',maxLines)+24};
 section('Job brief',parse.description,14);section('Dimensions and specification',parse.dimensions,9);section('Suggested materials',parse.materials,9);section('Completion requirements',parse.requirements||'Complete the task safely, accurately and to the issued specification. Check the finished work and correct defects before presenting it for assessment.',10);
 if(y<1370){const boxY=y+4,boxW=(W-2*M-24)/2;x.fillStyle=PALE;x.fillRect(M,boxY,boxW,210);x.fillRect(M+boxW+24,boxY,boxW,210);x.fillStyle=TEAL;x.font='700 22px Arial';x.fillText('Health and safety',M+20,boxY+34);x.fillText('Quality checks',M+boxW+44,boxY+34);drawLines('• Use required PPE and controls.\n• Inspect tools and equipment.\n• Maintain safe access and housekeeping.\n• Follow the relevant safe system of work.',M+20,boxY+70,boxW-40,27,'400 18px Arial',8);drawLines('• Check dimensions and setting out.\n• Maintain alignment and tolerances.\n• Check joints, fixings and finish.\n• Correct defects before completion.',M+boxW+44,boxY+70,boxW-40,27,'400 18px Arial',8)}
 x.fillStyle=TEAL;x.fillRect(0,H-70,W,70);x.fillStyle=WHITE;x.font='600 16px Arial';x.fillText('The assessor observes and marks the existing official KSB criteria.',M,H-28);x.textAlign='right';x.fillText(specificationId,W-M,H-28);x.textAlign='left';
 const bytes=dataUrlBytes(c.toDataURL('image/jpeg',0.92)),pdf=makeImagePDF([bytes],W,H),safe=clean(parse.title).replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').slice(0,50);downloadBlob(pdf,'application/pdf',`${safe||'Practical-Task'}-${specificationId}.pdf`);
}
